{"id":30315,"url":"https://patchwork.kernel.org/api/series/30315/?format=json","web_url":"https://patchwork.kernel.org/project/kvm/list/?series=30315","project":{"id":8,"url":"https://patchwork.kernel.org/api/projects/8/?format=json","name":"KVM mailing list","link_name":"kvm","list_id":"kvm.vger.kernel.org","list_email":"kvm@vger.kernel.org","web_url":null,"scm_url":null,"webscm_url":null},"name":"[1/2] kvm: x86: Bounds-check argument to x86_exception_has_error_code","date":"2018-10-12T18:04:28","submitter":{"id":169057,"url":"https://patchwork.kernel.org/api/people/169057/?format=json","name":"Jim Mattson","email":"jmattson@google.com"},"version":1,"total":2,"received_total":2,"received_all":true,"mbox":"https://patchwork.kernel.org/series/30315/mbox/","cover_letter":null,"patches":[{"id":10639081,"url":"https://patchwork.kernel.org/api/patches/10639081/?format=json","web_url":"https://patchwork.kernel.org/patch/10639081/","msgid":"<20181012180429.259916-1-jmattson@google.com>","date":"2018-10-12T18:04:28","name":"[1/2] kvm: x86: Bounds-check argument to x86_exception_has_error_code","mbox":"https://patchwork.kernel.org/patch/10639081/mbox/"},{"id":10639083,"url":"https://patchwork.kernel.org/api/patches/10639083/?format=json","web_url":"https://patchwork.kernel.org/patch/10639083/","msgid":"<20181012180429.259916-2-jmattson@google.com>","date":"2018-10-12T18:04:29","name":"[2/2] kvm: x86: Disallow invalid exceptions from userspace","mbox":"https://patchwork.kernel.org/patch/10639083/mbox/"}]}